name: test

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: npm build
        run: npm install && npm run build


